# Generated by Django 5.0 on 2024-01-18 06:29

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/images/user.jpg', null=True, upload_to=users.utils.user_directory_path),
        ),
    ]
