# Generated by Django 5.0 on 2024-01-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_location_city_manual_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city_manual',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
