# Generated by Django 5.0 on 2024-01-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_additionalimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
    ]
