# Generated by Django 5.0 on 2024-01-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_additionalimage'),
        ('users', '0009_location_city_manual_alter_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalimage',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
