# Generated by Django 5.0 on 2024-01-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_additionalimage_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
    ]
