# Generated by Django 5.0 on 2024-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_additionalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
