# Generated by Django 5.0 on 2024-02-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_listingimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
