# Generated by Django 5.0 on 2024-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='add_more_images',
            field=models.ManyToManyField(blank=True, to='main.listing'),
        ),
    ]
