# Generated by Django 5.0 on 2024-02-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_listing_add_more_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='add_more_images',
        ),
    ]
