# Generated by Django 5.0 on 2024-03-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_listingimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
