# Generated by Django 5.0 on 2026-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_delete_listingimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="vin",
        ),
        migrations.AlterField(
            model_name="listing",
            name="brand",
            field=models.CharField(
                choices=[
                    ("acura", "Acura"),
                    ("ashok leyland", "Ashok Leyland"),
                    ("audi", "Audi"),
                    ("bajaj", "Bajaj"),
                    ("bentley", "Bentley"),
                    ("bmw", "BMW"),
                    ("bugatti", "Bugatti"),
                    ("buick", "Buick"),
                    ("cadillac", "Cadillac"),
                    ("chevrolet", "Chevrolet"),
                    ("chrysler", "Chrysler"),
                    ("datsun", "Datsun"),
                    ("dodge", "Dodge"),
                    ("ferrari", "Ferrari"),
                    ("ford", "Ford"),
                    ("gmc", "GMC"),
                    ("honda", "Honda"),
                    ("hyundai", "Hyundai"),
                    ("isuzu", "Isuzu"),
                    ("jaguar", "Jaguar"),
                    ("jeep", "Jeep"),
                    ("kia", "Kia"),
                    ("lamborghini", "Lamborghini"),
                    ("land rover", "Land Rover"),
                    ("lexus", "Lexus"),
                    ("mahindra", "Mahindra"),
                    ("maruti suzuki", "Maruti Suzuki"),
                    ("maserati", "Maserati"),
                    ("mercedes benz", "Mercedes Benz"),
                    ("mg motor", "MG Motor"),
                    ("mini", "Mini"),
                    ("mitsubishi", "Mitsubishi"),
                    ("nissan", "Nissan"),
                    ("porsche", "Porsche"),
                    ("ram", "RAM"),
                    ("renault", "Renault"),
                    ("rolls royce", "Rolls Royce"),
                    ("skoda", "Skoda"),
                    ("subaru", "Subaru"),
                    ("tata motors", "Tata Motors"),
                    ("tesla", "Tesla"),
                    ("toyota", "Toyota"),
                    ("volkswagen", "Volkswagen"),
                    ("volvo", "Volvo"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=24,
            ),
        ),
    ]
